data_path: dataset.nosync/
framework: contrastive
text_backbone: bert-base-uncased
arch: transformer
workers: 8
epochs: 50
warmup_epochs: 5
start_epoch: 0
batch_size: 32
world_size: 1
lr: 0.0001
min_lr: 1.0e-09
rank: 0
dist_url: tcp://localhost:12312
dist_backend: nccl
seed: null
gpu: 0
print_freq: 50
multiprocessing_distributed: false
duration: 5.0
sr: 16000
num_chunks: 3
mel_dim: 128
n_fft: 1024
win_length: 1024
frontend: cnn
mix_type: cf
audio_rep: mel
cos: true
attention_nlayers: 4
attention_ndim: 256
temperature: 0.2
mlp_dim: 128
text_type: bert
text_rep: caption
disentangle: false
freeze: false
subset: true
log: true
device: cuda
distributed: false
text_dim: 768
audio_dim: 256
